trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  location: 'westus3'
  resourceGroupName: 'rg-iac-web-iis'
  vmName: 'vm-iac-web-iis'
  templateFile: 'vm-iis-template.json'
  parametersFile: 'vm-iis-parameters.json'
  indexUrl: 'https://raw.githubusercontent.com/lmlpuc/lmlarm003/refs/heads/main/src/index.html'
  scriptUrl: 'https://raw.githubusercontent.com/lmlpuc/lmlarm003/main/scripts/site.ps1'

stages:
- stage: DeployInfra
  displayName: 'Provisionar Infraestrutura'
  jobs:
  - job: Deploy
    displayName: 'Criar RG e recursos ARM'
    steps:
    - task: AzureCLI@2
      displayName: 'Criar Resource Group'
      inputs:
        azureSubscription: 'ar01com'  # 🔁 Substitua
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create --name $(resourceGroupName) --location $(location)

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy ARM Template'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'ar01com'  # 🔁 Substitua
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: 'arm-templates/vm-iis-template.json'
        csmParametersFile: 'arm-templates/vm-iis-parameters.json'
        deploymentMode: 'Incremental'
        deploymentName: 'vm-iis-deployment'

- stage: ConfigureWebsite
  displayName: 'Publicar site no IIS'
  dependsOn: DeployInfra
  jobs:
  - job: PublishHTML
    displayName: 'Executar CustomScriptExtension para copiar index.html'
    steps:
    - task: AzureCLI@2
      displayName: 'Executar CustomScriptExtension'
      inputs:
        azureSubscription: 'ar01com'  # 🔁 Substitua
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Script em linha salvo no host da VM
          $scriptContent = @"
          Invoke-WebRequest -Uri '$(indexUrl)' -OutFile 'C:\inetpub\wwwroot\index.html'
          "@

          $scriptContent | Out-File -Encoding ascii site.ps1

          az vm extension set `
            --resource-group $(resourceGroupName) `
            --vm-name $(vmName) `
            --name publishSiteExtension `
            --publisher Microsoft.Compute `
            --settings "{
              \"fileUris\": [\"https://raw.githubusercontent.com/lmlpuc/lmlarm003/main/src/scripts/site.ps1\"],
              \"commandToExecute\": \"powershell -ExecutionPolicy Unrestricted -File site.ps1\"
            }"
