trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  location: 'westus3'
  resourceGroupName: 'rg-iac-web-iis'
  vmName: 'vm-iac-web-iis'
  templateFile: 'vm-iis-template.json'
  parametersFile: 'vm-iis-parameters.json'
  indexUrl: 'https://raw.githubusercontent.com/lmlpuc/lmlarm003/refs/heads/main/src/index.html'
  scriptUrl: 'https://raw.githubusercontent.com/lmlpuc/lmlarm003/refs/heads/main/src/scripts/site.ps1' # Verifique se esta URL est치 correta

stages:
- stage: DeployInfra
  displayName: 'Provisionar Infraestrutura'
  jobs:
  - job: Deploy
    displayName: 'Criar RG e recursos ARM'
    steps:
    - task: AzureCLI@2
      displayName: 'Criar Resource Group'
      inputs:
        azureSubscription: 'ar01com'  # 游대 Substitua
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create --name $(resourceGroupName) --location $(location)

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy ARM Template'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'ar01com'  # 游대 Substitua
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: 'arm-templates/vm-iis-template.json'
        csmParametersFile: 'arm-templates/vm-iis-parameters.json'
        deploymentMode: 'Incremental'
        deploymentName: 'vm-iis-deployment'

- stage: ConfigureWebsite
  displayName: 'Publicar site no IIS'
  dependsOn: DeployInfra
  jobs:
  - job: PublishHTML
    displayName: 'Executar CustomScriptExtension para copiar index.html'
    steps:
    - task: AzureCLI@2
      displayName: 'Executar CustomScriptExtension'
      inputs:
        azureSubscription: 'ar01com'  # 游대 Substitua
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $vmName = '$(vmName)'
          $resourceGroup = '$(resourceGroupName)'
          $scriptUrl = '$(scriptUrl)'

          # Define o conte칰do JSON como um objeto PowerShell
          $settings = @{
            fileUris = @($scriptUrl)
            commandToExecute = "powershell -ExecutionPolicy Unrestricted -File site.ps1"
          }

          # Converte para JSON v치lido e salva em um arquivo tempor치rio no agente
          $jsonFile = "customScriptSettings.json"
          $settings | ConvertTo-Json -Depth 3 | Out-File -FilePath $jsonFile -Encoding ascii

          # Executa a extens칚o passando o caminho do arquivo JSON
          az vm extension set `
            --resource-group $resourceGroup `
            --vm-name $vmName `
            --name CustomScriptExtension `
            --publisher Microsoft.Compute `
            --settings @$jsonFile # Usa @ para indicar que 칠 um caminho de arquivo